### ISSUE TITLE
Aaron's weekly todo list

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/OrchestratingSingleCellAnalysis#8]
- [x] Replace spike-in example with `RichardTCellData()`.
- [x] Add cell cycle assignment chapter.
- [x] Discuss the relative nature of marker gene interpretation.

**Comment by LTLA** [comment]
Also add a better example for `denoisePCA`, as Zeisel just caps out at the `max.rank`.
